
GET http://localhost:3005/users


################################################################

POST http://localhost:3005/users
Content-Type: application/json

{
    "name": "chrisloarryn"
}

################################################################

GET http://localhost:3005/users/b0500955-91d4-4dce-8ae3-159b877ac686


################################################################

DELETE http://localhost:3005/users/b0500955-91d4-4dce-8ae3-159b877ac686


################################################################

PATCH http://localhost:3005/users/b0500955-91d4-4dce-8ae3-159b877ac686
Content-Type: application/json

{
    "name": "Peter J."
}